import os
from scipy.io import loadmat
from config import temp_path, perm_path

def load_data(patient, date, shift, batch, file_idx, folder, modality):
    """
    Loads a matlab timetable containing a specific EMG-ACM recording and its time-stamps (generated by TSG.mat)

    Args
    -------------------------------
    -patient: patient's assigned number/code without the 'p'.
    -date: date that appears in the file name in the format yyyymmdd.
    -shift: either 'D' (day/morning shift), 'A' (afternoon shift), or 'N' (night shift) as appears in file name.
    -batch: recording batch number as appears in file name. Note that files from the same date and shift have the same batch number.
    -file_idx: file number as appears in file name (file index within the batch).
    -folder: either 'temp' (temporary folder) or 'perm' (permanent folder), depending on the location of the file.
    -modality: either 'emg' (get EMG data only), 'acm' (get ACM data only), or 'both' (get both EMG and ACM data).

    Returns
    -------------------------------
    -data_ds: timetable containing the downsampled data as specified by input arguments.
    -time_s: timetable containing the equivalent time in seconds (to use as reference in the EMG and Motion Tools software).

    """
    # Convert to strings
    patient = str(patient)
    date = str(date)
    batch = str(batch)
    file_idx = str(file_idx)

    # Check the location of the file to load
    if folder == 'temp':
        path = temp_path
    
    elif folder == 'perm':
        path = perm_path

    # Load .mat file
    #dirpath = os.path.join(path, patient)
    dirpath = f"{path}{patient}"
    file_name = f"p{patient}_{date}_{shift}_{batch}_{file_idx}_TimeTable.mat"
    file = os.path.join(dirpath, file_name)
    data = loadmat(file)

    # Print keys in the loaded data to check what is available
    print(f"Keys in the loaded .mat file: {data.keys()}")

    # Check if 'data_with_timestamps' exists in the loaded data
    if 'data_with_timestamps' not in data:
        raise KeyError("'data_with_timestamps' not found in the .mat file")

    # Extract time in seconds (for Cometa software)
    time_s = data['data_with_timestamps'][:, 0]
    time_s = time_s[::2]  # downsample by a factor of 2

    # Extract either only EMG, only accelerometry, or both
    if modality == 'emg':
        data = data['data_with_timestamps'][:, 1:9] 
    elif modality == 'acm':
        data = data['data_with_timestamps'][:, 9:33] 
    elif modality == 'both':
        data = data['data_with_timestamps'][:, 1:33] 

    # Downsample data by a factor of 2
    data_ds = data[::2]

    return data_ds, time_s

data_ds, time_s = load_data(308, 20240703, 'A', 44, 5, 'temp', 'emg')

print("First 10 rows of Downsampled Data:")
print(data_ds[:10])

print("\nFirst 10 rows of Time in seconds:")
print(time_s[:10])
